### ISSUE TITLE
LocationList does not raise errors

### ISSUE THREAD

**Issue by mariuzka** [mariuzka/popy#46]
I noticed a strange behavior of LocationLists. LocationsLists expect two arguments: a model and a list of  (location-)objects.

In the following, you can see the correct use of LocationList:

![image](https://github.com/mariuzka/popy/assets/64357369/f876481d-a02d-4094-82b2-42d307bf2539)

However, if LocationList is used "wrong", it does not raise an error, but generates a LocationList of zero objects:

![image](https://github.com/mariuzka/popy/assets/64357369/9dc59e08-86ad-40ea-8e78-4da661e54188)

**Comment by luerhard** [comment]
Wenn wir Environment und Model stärker voneinander trennen wollen, finde ich die Voraussetzung, das Model zu übergeben eigentlich ziemlich doof für die LocationList, to be honest... Brauchen wir das unbedingt oder könnte man das nicht auch so schreiben, dass man das Model nicht braucht und sagt, die Hiearchie ist:

```
Model
    |-- hat Parameter Environment
        |-- hat Parameter locations vom Typ LocationList
    
```

Dann könnte man auch 
1. LocationLists ohne Model und Environment haben
2. Environments mit LocationLists ohne Model haben

**Comment by luerhard** [comment]
Hierzu kurz @mariuzka:

1. Das obere Beispiel wirft in der Tat keinen Fehler aus, das tut die AgentList allerdings auch nicht. Sollten sie das tun?
2. Im unteren Beispiel hast du eine leere LocationList angelegt und als Parameter angegeben: `LocationList(model=[1,2])`. Meinst du, wir sollten da noch den Typ von Model überprüfen? I don't know...

**Comment by mariuzka** [comment]
Ja keine Ahnung, mir ist es halt schon öfter passiert, dass ich die AgentList falsch  verwendet habe (habe kein Model eingegeben) und ich dann sehr sehr lange nach dem Fehler gesucht habe. Eine Möglichkeit wäre natürlich bei `objs` den Default-Wert wegzumachen, damit Python rummeckert, wenn man das vergisst. Aber wir können es auch einfach so lassen!

**Comment by luerhard** [comment]
Man könnte einfach nur den isistance von Model prüfen, das wäre einigermaßen günstig (verglichen mit alle Elemente aus der Liste zu checken). 

Aber ja. Evtl macht auch den default von objs löschen Sinn.
